// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Z1lC3yR_MhusTjMB_7ACIiK0P6yKbBE',
    appId: '1:167403882189:web:9a111b803524365b914b84',
    messagingSenderId: '167403882189',
    projectId: 'login-and-sign-in-app',
    authDomain: 'login-and-sign-in-app.firebaseapp.com',
    databaseURL: 'https://login-and-sign-in-app-default-rtdb.firebaseio.com',
    storageBucket: 'login-and-sign-in-app.firebasestorage.app',
    measurementId: 'G-XNMLSMDG2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ5wuDBJzcZcztqLq7TluyXWRAZzM0vmc',
    appId: '1:167403882189:android:ce32d00e676ca0d1914b84',
    messagingSenderId: '167403882189',
    projectId: 'login-and-sign-in-app',
    databaseURL: 'https://login-and-sign-in-app-default-rtdb.firebaseio.com',
    storageBucket: 'login-and-sign-in-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF555GJLemXMDtMdv4UY2cTlc8rqHl2pg',
    appId: '1:167403882189:ios:bb3b3d8e395f72c9914b84',
    messagingSenderId: '167403882189',
    projectId: 'login-and-sign-in-app',
    databaseURL: 'https://login-and-sign-in-app-default-rtdb.firebaseio.com',
    storageBucket: 'login-and-sign-in-app.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF555GJLemXMDtMdv4UY2cTlc8rqHl2pg',
    appId: '1:167403882189:ios:bb3b3d8e395f72c9914b84',
    messagingSenderId: '167403882189',
    projectId: 'login-and-sign-in-app',
    databaseURL: 'https://login-and-sign-in-app-default-rtdb.firebaseio.com',
    storageBucket: 'login-and-sign-in-app.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );
}
